version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: studentshub-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - "80:80"
      - "443:443"

  mongodb:
    image: mongo:latest
    container_name: studentshub-mongodb
    volumes:
      - ~/apps/mongo:/data/db
    ports:
      - "27017"

  websocket:
    image: node:latest
    container_name: studentshub-websocket
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm run websocket"
    ports:
      - "3000"
    environment:
      - DOCKER=true
      - NODE_ENV=development
      - WEBSOCKET_PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/studentshub

  node1:
    image: node:latest
    container_name: studentshub-node1
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm start"
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
      - DOCKER=true
      - NODE_ENV=development
      - NODE_PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/studentshub

  node2:
    image: node:latest
    container_name: studentshub-node2
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm start"
    ports:
      - "3000"
    environment:
      - INSTANCE=node2
      - DOCKER=true
      - NODE_ENV=development
      - NODE_PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/studentshub

  node3:
    image: node:latest
    container_name: studentshub-node3
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm start"
    ports:
      - "3000"
    environment:
      - INSTANCE=node3
      - DOCKER=true
      - NODE_ENV=development
      - NODE_PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/studentshub
