version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: studentshub-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - node
    ports:
      - "80:80"
      - "443:443"

  mongodb:
    image: mongo:latest
    container_name: studentshub-mongodb
    volumes:
      - ~/apps/mongo:/data/db
    ports:
      - "27017"

  node:
    image: node:latest
    container_name: studentshub-node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm start"
    ports:
      - "3000"
      - "3001"
    environment:
      - DOCKER=true
      - NODE_ENV=development
      - NODE_PORT=3000
      - WEBSOCKET_PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/studentshub
